name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm run typeCheck

      - name: Lint
        run: pnpm run format

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
        # run: pnpm run test --coverage

      # - name: Upload test coverage
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: ./coverage
      #     if-no-files-found: ignore

      # https://github.com/cloudflare/wrangler-action
      - name: Deploy Worker
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
